apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  labels:
    tier: backend
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
      tier: backend
  template:
    metadata:
      labels:
        app: nginx2
        tier: backend
    spec:
      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: php2-backend-pvc
      - name: config
        configMap:
          name: nginx2-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx2
        image: nginx
        volumeMounts:
        - mountPath: /code
          name: static
        - name: config
          mountPath: /etc/nginx/conf.d
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: nginx2
  labels:
    tier: backend
    app: nginx2
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31020
  selector:
    tier: backend
    app: nginx2
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx2-config
  labels:
    tier: backend
data:
  config : |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      
      root /code/app/public;
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }
      
      location ~ .php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+.php)(/.+)$;
          fastcgi_pass php2:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }
