apiVersion: apps/v1
kind: Deployment
metadata:
  name: php2
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php2
      tier: backend
  template:
    metadata:
      labels:
        app: php2
        tier: backend
    spec:
      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: php2-backend-pvc
      containers:
      - name: php2
        #image: shoeb0005/laravel-app1
        image: shoeb0005/app2
        imagePullPolicy: Always
        volumeMounts:
         - mountPath: /code
           name: static
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -apr /var/www/. /code/app"]
      tolerations:
        - key: "label"
          value: "node02"
          operator: "Equal"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: php
                operator: In
                values:
                - app02
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
         - mountPath: /code
           name: static
        command: ["/bin/sh", "-c", "cp -apr /var/www/. /code/app"]   
       # command:
       # - cp
       # - "-apr"
       # - "/var/www/."
       # - "/code/app"
---
apiVersion: v1
kind: Service
metadata:
  name: php2
  labels:
    tier: backend
spec:
  selector:
    app: php2
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php2-backend-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/code2"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php2-backend-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
